# Generated by Django 5.2.5 on 2025-08-28 07:16

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInnerPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Card Title', max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FaqItemPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('question', models.CharField(default='Non consectetur a erat nam at lectus urna duis?', max_length=300, verbose_name='Question')),
                ('answer', models.TextField(default='Feugiat pretium nibh ipsum consequat. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non.', verbose_name='Answer')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active by Default (faq-active)')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FaqSectionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='F.A.Q', max_length=200, verbose_name='Section Title')),
                ('subtitle_part1', models.CharField(default='Frequently Asked', max_length=200, verbose_name='Subtitle Part 1')),
                ('subtitle_part2', models.CharField(default='Questions', max_length=200, verbose_name='Subtitle Part 2')),
                ('aos_delay', models.CharField(default='100', max_length=10, verbose_name='AOS Delay for Section')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ServiceTilePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('icon_class', models.CharField(default='bi bi-calendar4-week', max_length=100, verbose_name='Bootstrap Icon Class')),
                ('aos_delay', models.CharField(default='300', max_length=10, verbose_name='AOS Delay')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AboutSectionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='About', max_length=200, verbose_name='Section Title')),
                ('subtitle_part1', models.CharField(default='Find Out More', max_length=200, verbose_name='Subtitle Part 1')),
                ('subtitle_part2', models.CharField(default='About Us', max_length=200, verbose_name='Subtitle Part 2')),
                ('main_heading', models.CharField(default='Voluptatem dignissimos provident quasi corporis voluptates sit assumenda.', max_length=300, verbose_name='Main Heading')),
                ('italic_text', models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', verbose_name='Italic Text')),
                ('aos_delay_image', models.CharField(default='100', max_length=10, verbose_name='AOS Delay for Image')),
                ('aos_delay_content', models.CharField(default='200', max_length=10, verbose_name='AOS Delay for Content')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_section_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HeroSectionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title_part1', models.CharField(default='Приветствуем в', max_length=200, verbose_name='Title Part 1')),
                ('title_part2', models.CharField(default='ФБГУ НИИ Интеграл', max_length=200, verbose_name='Title Part 2 (Highlighted)')),
                ('description', models.TextField(blank=True, default='Ведомственная принадлежность: ФГБУ НИИ «Интеграл» находится в ведении Министерства цифрового развития, связи и массовых коммуникаций Российской Федерации', null=True, verbose_name='Description')),
                ('get_started_text', models.CharField(default='Get Started', max_length=100, verbose_name='Get Started Button Text')),
                ('get_started_url', models.CharField(blank=True, default='#about', max_length=200, verbose_name='Get Started Button URL')),
                ('telegram_text', models.CharField(blank=True, default='Телеграмм канал', max_length=100, verbose_name='Telegram Button Text')),
                ('telegram_url', models.CharField(blank=True, default='https://t.me/integral_security', max_length=200, verbose_name='Telegram Button URL')),
                ('aos_animation', models.CharField(blank=True, default='zoom-out', max_length=50, verbose_name='AOS Animation')),
                ('background_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_background_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Background Image')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
