# Generated by Django 5.2.5 on 2025-08-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indepo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardinnerpluginmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='herosectionpluginmodel',
            name='description',
        ),
    ]
