# Generated by Django 5.2.5 on 2025-08-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indepo', '0002_remove_cardinnerpluginmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitempluginmodel',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faqitempluginmodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='faqitempluginmodel',
            name='question',
            field=models.CharField(default='Вопрос', max_length=200, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faqsectionpluginmodel',
            name='aos_delay',
            field=models.PositiveIntegerField(default=100, verbose_name='AOS Delay'),
        ),
        migrations.AlterField(
            model_name='faqsectionpluginmodel',
            name='subtitle_part1',
            field=models.CharField(default='Имеются вопросы?', max_length=200, verbose_name='Subtitle Part 1'),
        ),
        migrations.AlterField(
            model_name='faqsectionpluginmodel',
            name='subtitle_part2',
            field=models.CharField(default='Ознакомьтесь с нашими FAQ', max_length=200, verbose_name='Subtitle Part 2'),
        ),
        migrations.AlterField(
            model_name='faqsectionpluginmodel',
            name='title',
            field=models.CharField(default='Часто задаваемые вопросы', max_length=200, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='CardInnerPluginModel',
        ),
    ]
