# Generated by Django 5.2.5 on 2025-08-28 08:45

import djangocms_text_ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indepo', '0003_alter_faqitempluginmodel_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitempluginmodel',
            name='answer',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Answer'),
        ),
    ]
