# Generated by Django 5.2.5 on 2025-08-28 12:01

import djangocms_text_ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indepo', '0004_alter_faqitempluginmodel_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosectionpluginmodel',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='Здесь можно написать описание секции', null=True, verbose_name='Description'),
        ),
    ]
