# Generated by Django 5.2.5 on 2025-08-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indepo', '0005_herosectionpluginmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosectionpluginmodel',
            name='description',
        ),
    ]
