# Generated by Django 5.2.5 on 2025-08-28 12:24

import djangocms_text_ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indepo', '0006_remove_herosectionpluginmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosectionpluginmodel',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='Ведомственная принадлежность: ФГБУ НИИ «Интеграл» находится в ведении Министерства цифрового развития, связи и массовых коммуникаций Российской Федерации', null=True, verbose_name='Description Text'),
        ),
        migrations.AlterField(
            model_name='herosectionpluginmodel',
            name='title_part2',
            field=models.CharField(default='ФБГУ НИИ "Интеграл"', max_length=200, verbose_name='Title Part 2 (Highlighted)'),
        ),
    ]
