# Generated by Django 5.2.5 on 2025-08-29 08:03

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('indepo', '0007_herosectionpluginmodel_description_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsectionpluginmodel',
            name='aos_delay_content',
        ),
        migrations.RemoveField(
            model_name='aboutsectionpluginmodel',
            name='aos_delay_image',
        ),
        migrations.RemoveField(
            model_name='aboutsectionpluginmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutsectionpluginmodel',
            name='italic_text',
        ),
        migrations.RemoveField(
            model_name='aboutsectionpluginmodel',
            name='main_heading',
        ),
        migrations.CreateModel(
            name='AboutItemPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('main_heading', models.CharField(max_length=300, verbose_name='Main Heading')),
                ('italic_text', models.TextField(blank=True, null=True, verbose_name='Italic Text')),
                ('aos_delay_image', models.CharField(default='100', max_length=10, verbose_name='AOS Delay for Image')),
                ('aos_delay_content', models.CharField(default='200', max_length=10, verbose_name='AOS Delay for Content')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_item_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
