# Generated by Django 5.2.5 on 2025-09-02 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('indepo', '0008_remove_aboutsectionpluginmodel_aos_delay_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItemPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon_class', models.CharField(default='bi bi-activity', help_text="Например: 'bi bi-activity'", max_length=100, verbose_name='Icon CSS class')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('aos_delay', models.PositiveIntegerField(default=100, verbose_name='AOS delay (ms)')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ServicesSectionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Services', max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, default='Check Our Services', max_length=200, verbose_name='Subtitle')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TestimonialItemPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('author_name', models.CharField(max_length=200, verbose_name='Author name')),
                ('author_role', models.CharField(blank=True, max_length=200, verbose_name='Author role')),
                ('quote', models.TextField(verbose_name='Quote')),
                ('image', models.CharField(blank=True, help_text='например: assets/img/testimonials/testimonials-1.jpg', max_length=255, verbose_name='Image (static path)')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TestimonialsSectionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Testimonials', max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, default='', max_length=200, verbose_name='Subtitle')),
                ('background', models.CharField(blank=True, default='assets/img/testimonials-bg.jpg', max_length=255, verbose_name='Background image (static path)')),
                ('swiper_config', models.TextField(blank=True, default='{"loop": true, "speed": 600, "autoplay": {"delay": 5000}, "slidesPerView": "auto", "pagination": {"el": ".swiper-pagination", "type": "bullets", "clickable": true}}', verbose_name='Swiper JSON config')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TopBarPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('email', models.EmailField(default='contact@example.com', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='+1 5589 55488 55', max_length=50, verbose_name='Телефон')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('vk', models.URLField(blank=True, null=True, verbose_name='ВКонтакте')),
                ('odnoklassniki', models.URLField(blank=True, null=True, verbose_name='Одноклассники')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
