server {
    listen 80;
    server_name indepo.occert.ru;

    client_max_body_size 20m;

    gzip on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_types
        text/plain
        text/css
        application/javascript
        application/json
        application/xml
        text/xml
        application/rss+xml
        image/svg+xml;
    gzip_vary on;

    # Статика и медиа (томы примонтированы в /static и /media)
    location /static/ {
        alias /static/;
        access_log off;
        add_header Cache-Control "public, max-age=31536000, immutable" always;
    }
    location /file/ {
        alias /media/;
        access_log off;
        add_header Cache-Control "public, max-age=31536000, immutable" always;
    }
    # Прокси на gunicorn (web:8000 это имя сервиса docker-compose)
    location / {
        add_header Cache-Control "no-cache, no-store, must-revalidate" always;
        proxy_pass         http://web:8000;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
    }
}
