# Generated by Django 5.2.5 on 2025-08-30 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBarPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('email', models.EmailField(default='contact@example.com', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='+1 5589 55488 55', max_length=50, verbose_name='Телефон')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
