# Generated by Django 5.2.5 on 2025-08-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_indepo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topbarpluginmodel',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='topbarpluginmodel',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='topbarpluginmodel',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='topbarpluginmodel',
            name='twitter',
        ),
        migrations.AddField(
            model_name='topbarpluginmodel',
            name='odnoklassniki',
            field=models.URLField(blank=True, null=True, verbose_name='Одноклассники'),
        ),
        migrations.AddField(
            model_name='topbarpluginmodel',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='topbarpluginmodel',
            name='vk',
            field=models.URLField(blank=True, null=True, verbose_name='ВКонтакте'),
        ),
    ]
