# Generated by Django 5.2.5 on 2025-08-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_indepo', '0004_alter_testimonialssectionpluginmodel_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialssectionpluginmodel',
            name='background',
            field=models.CharField(blank=True, default='assets/img/testimonials-bg.jpg', max_length=255, verbose_name='Background image (static path)'),
        ),
    ]
