# Generated by Django 5.2.5 on 2025-09-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_indepo', '0006_teamcontainer_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='odnoklassniki',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='vk',
        ),
    ]
