# Generated by Django 5.2.5 on 2025-09-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_indepo', '0007_remove_teammember_odnoklassniki_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamcontainer',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='teammember',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='teamcontainer',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
