# Generated by Django 5.2.5 on 2025-09-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_indepo', '0008_remove_teamcontainer_subtitle_teammember_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcontainer',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='teamcontainer',
            name='title',
            field=models.CharField(default='Team', max_length=200),
        ),
    ]
