# Generated by Django 5.2.5 on 2025-09-02 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('test_indepo', '0009_teamcontainer_description_alter_teamcontainer_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSectionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Contact', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('yandex_map', models.TextField(help_text='Вставьте iframe-код карты из конструктора Яндекс.Карт', verbose_name='Код Яндекс карты (iframe)')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
