# Generated by Django 5.2.5 on 2025-09-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('test_indepo', '0010_contactsectionpluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfoPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('address', models.CharField(default='A108 Adam Street, New York, NY 535022', max_length=255)),
                ('phone', models.CharField(default='+1 5589 55488 55', max_length=50)),
                ('email', models.EmailField(default='info@example.com', max_length=254)),
                ('map_iframe', models.TextField(default='<iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A..." width="100%" height="270" frameborder="0"></iframe>', help_text='Вставьте iframe карты Яндекс')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.DeleteModel(
            name='ContactSectionPluginModel',
        ),
    ]
