# Generated by Django 5.2.5 on 2025-09-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_indepo', '0011_contactinfopluginmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfopluginmodel',
            name='subtitle',
            field=models.CharField(default="<span>Need Help?</span> <span class='description-title'>Contact Us</span>", max_length=255),
        ),
        migrations.AddField(
            model_name='contactinfopluginmodel',
            name='title',
            field=models.CharField(default='Contact', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfopluginmodel',
            name='map_iframe',
            field=models.TextField(default='<iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A..." width="100%" height="400" frameborder="0"></iframe>', help_text='Вставьте iframe карты Яндекс'),
        ),
    ]
