# Generated by Django 5.2.5 on 2025-09-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('test_indepo', '0012_contactinfopluginmodel_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('copyright_text', models.CharField(default='All Rights Reserved', max_length=255, verbose_name='Текст копирайта')),
                ('site_name', models.CharField(default='BizLand', max_length=100, verbose_name='Название сайта')),
                ('designed_by', models.CharField(default='BootstrapMade', max_length=100, verbose_name='Кем разработан')),
                ('designed_by_url', models.URLField(default='https://bootstrapmade.com/', verbose_name='Ссылка на разработчика')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
