# Generated by Django 5.2.5 on 2025-09-02 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('test_indepo', '0013_footerpluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedServiceItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('icon', models.CharField(default='bi bi-activity', max_length=50, verbose_name='Bootstrap Icon класс')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('delay', models.PositiveIntegerField(default=100, verbose_name='Анимация (delay в ms)')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FeaturedServicesSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Featured Services', max_length=200, verbose_name='Заголовок секции')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
