# Generated by Django 5.2.5 on 2025-09-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_indepo', '0014_featuredserviceitem_featuredservicessection'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredservicessection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='featuredservicessection',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
