# Generated by Django 5.2.7 on 2025-10-07

import django.db.models.deletion
import parler.fields
import parler.models
from cms.models.pluginmodel import CMSPlugin
from django.db import migrations, models
from django.db.migrations.operations.base import Operation

import test_indepo.models


class AlterModelBases(Operation):
    """Update model bases in migration state only."""

    reduces_to_sql = False

    def __init__(self, name, new_bases, old_bases):
        self.name = name
        self.new_bases = new_bases
        self.old_bases = old_bases

    def deconstruct(self):
        return (
            self.__class__.__qualname__,
            [self.name, self.new_bases, self.old_bases],
            {},
        )

    def state_forwards(self, app_label, state):
        model_state = state.models[app_label, self.name.lower()]
        model_state.bases = self.new_bases

    def state_backwards(self, app_label, state):
        model_state = state.models[app_label, self.name.lower()]
        model_state.bases = self.old_bases

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        pass

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        pass

    @property
    def reversible(self):
        return True


DEFAULT_LANGUAGES = ("ru", "en")


def seed_translations(apps, schema_editor):
    mapping = [
        (
            "ServicesSectionPluginModel",
            "ServicesSectionPluginModelTranslation",
            {"title_legacy": "title", "subtitle_legacy": "subtitle"},
        ),
        (
            "ServiceItemPluginModel",
            "ServiceItemPluginModelTranslation",
            {"title_legacy": "title", "description_legacy": "description"},
        ),
        (
            "TestimonialsSectionPluginModel",
            "TestimonialsSectionPluginModelTranslation",
            {"title_legacy": "title", "subtitle_legacy": "subtitle"},
        ),
        (
            "TestimonialItemPluginModel",
            "TestimonialItemPluginModelTranslation",
            {
                "author_name_legacy": "author_name",
                "author_role_legacy": "author_role",
                "quote_legacy": "quote",
            },
        ),
        (
            "TeamContainer",
            "TeamContainerTranslation",
            {"title_legacy": "title", "description_legacy": "description"},
        ),
        (
            "TeamMember",
            "TeamMemberTranslation",
            {"name_legacy": "name", "role_legacy": "role", "subtitle_legacy": "subtitle"},
        ),
        (
            "ContactInfoPluginModel",
            "ContactInfoPluginModelTranslation",
            {
                "title_legacy": "title",
                "subtitle_legacy": "subtitle",
                "address_legacy": "address",
            },
        ),
        (
            "FooterPluginModel",
            "FooterPluginModelTranslation",
            {
                "copyright_text_legacy": "copyright_text",
                "site_name_legacy": "site_name",
                "designed_by_legacy": "designed_by",
            },
        ),
        (
            "FeaturedServicesSection",
            "FeaturedServicesSectionTranslation",
            {"title_legacy": "title", "description_legacy": "description"},
        ),
        (
            "FeaturedServiceItem",
            "FeaturedServiceItemTranslation",
            {"title_legacy": "title", "description_legacy": "description"},
        ),
    ]

    for model_name, translation_name, field_map in mapping:
        model = apps.get_model("test_indepo", model_name)
        translation_model = apps.get_model("test_indepo", translation_name)
        for instance in model.objects.all():
            payload = {
                new_field: getattr(instance, old_field, None)
                for old_field, new_field in field_map.items()
            }
            for language_code in DEFAULT_LANGUAGES:
                translation_model.objects.create(
                    master_id=instance.pk,
                    language_code=language_code,
                    **payload,
                )


def unseed_translations(apps, schema_editor):
    translation_models = [
        "ServicesSectionPluginModelTranslation",
        "ServiceItemPluginModelTranslation",
        "TestimonialsSectionPluginModelTranslation",
        "TestimonialItemPluginModelTranslation",
        "TeamContainerTranslation",
        "TeamMemberTranslation",
        "ContactInfoPluginModelTranslation",
        "FooterPluginModelTranslation",
        "FeaturedServicesSectionTranslation",
        "FeaturedServiceItemTranslation",
    ]
    for model_name in translation_models:
        translation_model = apps.get_model("test_indepo", model_name)
        translation_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("test_indepo", "0015_featuredservicessection_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactinfopluginmodel",
            old_name="title",
            new_name="title_legacy",
        ),
        migrations.RenameField(
            model_name="contactinfopluginmodel",
            old_name="subtitle",
            new_name="subtitle_legacy",
        ),
        migrations.RenameField(
            model_name="contactinfopluginmodel",
            old_name="address",
            new_name="address_legacy",
        ),
        migrations.RenameField(
            model_name="featuredserviceitem",
            old_name="title",
            new_name="title_legacy",
        ),
        migrations.RenameField(
            model_name="featuredserviceitem",
            old_name="description",
            new_name="description_legacy",
        ),
        migrations.RenameField(
            model_name="featuredservicessection",
            old_name="title",
            new_name="title_legacy",
        ),
        migrations.RenameField(
            model_name="featuredservicessection",
            old_name="description",
            new_name="description_legacy",
        ),
        migrations.RenameField(
            model_name="footerpluginmodel",
            old_name="site_name",
            new_name="site_name_legacy",
        ),
        migrations.RenameField(
            model_name="footerpluginmodel",
            old_name="copyright_text",
            new_name="copyright_text_legacy",
        ),
        migrations.RenameField(
            model_name="footerpluginmodel",
            old_name="designed_by",
            new_name="designed_by_legacy",
        ),
        migrations.RenameField(
            model_name="serviceitempluginmodel",
            old_name="title",
            new_name="title_legacy",
        ),
        migrations.RenameField(
            model_name="serviceitempluginmodel",
            old_name="description",
            new_name="description_legacy",
        ),
        migrations.RenameField(
            model_name="servicessectionpluginmodel",
            old_name="title",
            new_name="title_legacy",
        ),
        migrations.RenameField(
            model_name="servicessectionpluginmodel",
            old_name="subtitle",
            new_name="subtitle_legacy",
        ),
        migrations.RenameField(
            model_name="teamcontainer",
            old_name="title",
            new_name="title_legacy",
        ),
        migrations.RenameField(
            model_name="teamcontainer",
            old_name="description",
            new_name="description_legacy",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="name",
            new_name="name_legacy",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="role",
            new_name="role_legacy",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="subtitle",
            new_name="subtitle_legacy",
        ),
        migrations.RenameField(
            model_name="testimonialitempluginmodel",
            old_name="author_name",
            new_name="author_name_legacy",
        ),
        migrations.RenameField(
            model_name="testimonialitempluginmodel",
            old_name="author_role",
            new_name="author_role_legacy",
        ),
        migrations.RenameField(
            model_name="testimonialitempluginmodel",
            old_name="quote",
            new_name="quote_legacy",
        ),
        migrations.RenameField(
            model_name="testimonialssectionpluginmodel",
            old_name="title",
            new_name="title_legacy",
        ),
        migrations.RenameField(
            model_name="testimonialssectionpluginmodel",
            old_name="subtitle",
            new_name="subtitle_legacy",
        ),
        AlterModelBases(
            name="servicessectionpluginmodel",
            new_bases=(test_indepo.models.TranslatableCMSPlugin,),
            old_bases=(CMSPlugin,),
        ),
        AlterModelBases(
            name="serviceitempluginmodel",
            new_bases=(test_indepo.models.TranslatableCMSPlugin,),
            old_bases=(CMSPlugin,),
        ),
        AlterModelBases(
            name="testimonialssectionpluginmodel",
            new_bases=(test_indepo.models.TranslatableCMSPlugin,),
            old_bases=(CMSPlugin,),
        ),
        AlterModelBases(
            name="testimonialitempluginmodel",
            new_bases=(test_indepo.models.TranslatableCMSPlugin,),
            old_bases=(CMSPlugin,),
        ),
        AlterModelBases(
            name="teamcontainer",
            new_bases=(test_indepo.models.TranslatableCMSPlugin,),
            old_bases=(CMSPlugin,),
        ),
        AlterModelBases(
            name="teammember",
            new_bases=(test_indepo.models.TranslatableCMSPlugin,),
            old_bases=(CMSPlugin,),
        ),
        AlterModelBases(
            name="contactinfopluginmodel",
            new_bases=(test_indepo.models.TranslatableCMSPlugin,),
            old_bases=(CMSPlugin,),
        ),
        AlterModelBases(
            name="footerpluginmodel",
            new_bases=(test_indepo.models.TranslatableCMSPlugin,),
            old_bases=(CMSPlugin,),
        ),
        AlterModelBases(
            name="featuredservicessection",
            new_bases=(test_indepo.models.TranslatableCMSPlugin,),
            old_bases=(CMSPlugin,),
        ),
        AlterModelBases(
            name="featuredserviceitem",
            new_bases=(test_indepo.models.TranslatableCMSPlugin,),
            old_bases=(CMSPlugin,),
        ),
        migrations.CreateModel(
            name="ContactInfoPluginModelTranslation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("title", models.CharField(default="Contact", max_length=100)),
                (
                    "subtitle",
                    models.CharField(
                        default="<span>Need Help?</span> <span class='description-title'>Contact Us</span>",
                        max_length=255,
                    ),
                ),
                ("address", models.CharField(default="A108 Adam Street, New York, NY 535022", max_length=255)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="test_indepo.contactinfopluginmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "contact info plugin model Translation",
                "db_table": "test_indepo_contactinfopluginmodel_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FeaturedServiceItemTranslation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="test_indepo.featuredserviceitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "featured service item Translation",
                "db_table": "test_indepo_featuredserviceitem_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FeaturedServicesSectionTranslation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("title", models.CharField(blank=True, max_length=200, null=True, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="test_indepo.featuredservicessection",
                    ),
                ),
            ],
            options={
                "verbose_name": "featured services section Translation",
                "db_table": "test_indepo_featuredservicessection_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FooterPluginModelTranslation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("copyright_text", models.CharField(default="All Rights Reserved", max_length=255, verbose_name="Текст копирайта")),
                ("site_name", models.CharField(default="BizLand", max_length=100, verbose_name="Название сайта")),
                ("designed_by", models.CharField(default="BootstrapMade", max_length=100, verbose_name="Кем разработан")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="test_indepo.footerpluginmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "footer plugin model Translation",
                "db_table": "test_indepo_footerpluginmodel_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ServiceItemPluginModelTranslation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="test_indepo.serviceitempluginmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "service item plugin model Translation",
                "db_table": "test_indepo_serviceitempluginmodel_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ServicesSectionPluginModelTranslation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("title", models.CharField(default="Services", max_length=200, verbose_name="Title")),
                ("subtitle", models.CharField(blank=True, default="Check Our Services", max_length=200, verbose_name="Subtitle")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="test_indepo.servicessectionpluginmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "services section plugin model Translation",
                "db_table": "test_indepo_servicessectionpluginmodel_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TeamContainerTranslation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("title", models.CharField(default="Team", max_length=200)),
                ("description", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="test_indepo.teamcontainer",
                    ),
                ),
            ],
            options={
                "verbose_name": "team container Translation",
                "db_table": "test_indepo_teamcontainer_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TeamMemberTranslation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("name", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="test_indepo.teammember",
                    ),
                ),
            ],
            options={
                "verbose_name": "team member Translation",
                "db_table": "test_indepo_teammember_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TestimonialItemPluginModelTranslation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("author_name", models.CharField(max_length=200, verbose_name="Author name")),
                ("author_role", models.CharField(blank=True, max_length=200, verbose_name="Author role")),
                ("quote", models.TextField(verbose_name="Quote")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="test_indepo.testimonialitempluginmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "testimonial item plugin model Translation",
                "db_table": "test_indepo_testimonialitempluginmodel_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TestimonialsSectionPluginModelTranslation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("title", models.CharField(default="Testimonials", max_length=200, verbose_name="Title")),
                ("subtitle", models.CharField(blank=True, default="", max_length=200, verbose_name="Subtitle")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="test_indepo.testimonialssectionpluginmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "testimonials section plugin model Translation",
                "db_table": "test_indepo_testimonialssectionpluginmodel_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RunPython(seed_translations, unseed_translations),
        migrations.RemoveField(
            model_name="contactinfopluginmodel",
            name="address_legacy",
        ),
        migrations.RemoveField(
            model_name="contactinfopluginmodel",
            name="subtitle_legacy",
        ),
        migrations.RemoveField(
            model_name="contactinfopluginmodel",
            name="title_legacy",
        ),
        migrations.RemoveField(
            model_name="featuredserviceitem",
            name="description_legacy",
        ),
        migrations.RemoveField(
            model_name="featuredserviceitem",
            name="title_legacy",
        ),
        migrations.RemoveField(
            model_name="featuredservicessection",
            name="description_legacy",
        ),
        migrations.RemoveField(
            model_name="featuredservicessection",
            name="title_legacy",
        ),
        migrations.RemoveField(
            model_name="footerpluginmodel",
            name="copyright_text_legacy",
        ),
        migrations.RemoveField(
            model_name="footerpluginmodel",
            name="designed_by_legacy",
        ),
        migrations.RemoveField(
            model_name="footerpluginmodel",
            name="site_name_legacy",
        ),
        migrations.RemoveField(
            model_name="serviceitempluginmodel",
            name="description_legacy",
        ),
        migrations.RemoveField(
            model_name="serviceitempluginmodel",
            name="title_legacy",
        ),
        migrations.RemoveField(
            model_name="servicessectionpluginmodel",
            name="subtitle_legacy",
        ),
        migrations.RemoveField(
            model_name="servicessectionpluginmodel",
            name="title_legacy",
        ),
        migrations.RemoveField(
            model_name="teamcontainer",
            name="description_legacy",
        ),
        migrations.RemoveField(
            model_name="teamcontainer",
            name="title_legacy",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="name_legacy",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="plugin",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="role_legacy",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="subtitle_legacy",
        ),
        migrations.RemoveField(
            model_name="testimonialitempluginmodel",
            name="author_name_legacy",
        ),
        migrations.RemoveField(
            model_name="testimonialitempluginmodel",
            name="author_role_legacy",
        ),
        migrations.RemoveField(
            model_name="testimonialitempluginmodel",
            name="quote_legacy",
        ),
        migrations.RemoveField(
            model_name="testimonialssectionpluginmodel",
            name="subtitle_legacy",
        ),
        migrations.RemoveField(
            model_name="testimonialssectionpluginmodel",
            name="title_legacy",
        ),
        migrations.AlterField(
            model_name="testimonialssectionpluginmodel",
            name="swiper_config",
            field=models.JSONField(
                blank=True,
                default=test_indepo.models.default_swiper_config,
                verbose_name="Swiper JSON config",
            ),
        ),
    ]
