# Generated by Django 5.2.7 on 2025-10-07 19:09

import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('test_indepo', '0016_add_translations'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSectionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, 'cms.cmsplugin'),
        ),
        migrations.CreateModel(
            name='FaqItemPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, 'cms.cmsplugin'),
        ),
        migrations.CreateModel(
            name='FaqSectionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('aos_delay', models.PositiveIntegerField(default=100, verbose_name='AOS delay (ms)')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, 'cms.cmsplugin'),
        ),
        migrations.CreateModel(
            name='ServiceTilePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('icon_class', models.CharField(default='bi bi-calendar4-week', max_length=100, verbose_name='Bootstrap icon class')),
                ('aos_delay', models.PositiveIntegerField(default=300, verbose_name='AOS delay (ms)')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, 'cms.cmsplugin'),
        ),
        migrations.CreateModel(
            name='AboutItemPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('aos_delay_image', models.PositiveIntegerField(default=100, verbose_name='AOS delay for image (ms)')),
                ('aos_delay_content', models.PositiveIntegerField(default=200, verbose_name='AOS delay for content (ms)')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, 'cms.cmsplugin'),
        ),
        migrations.CreateModel(
            name='HeroSectionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('get_started_url', models.CharField(blank=True, default='#about', max_length=200, verbose_name='Primary button URL')),
                ('telegram_url', models.CharField(blank=True, default='https://t.me/integral_security', max_length=200, verbose_name='Secondary button URL')),
                ('aos_animation', models.CharField(blank=True, default='zoom-out', max_length=50, verbose_name='AOS animation')),
                ('background_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Background image')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, 'cms.cmsplugin'),
        ),
        migrations.CreateModel(
            name='AboutItemPluginModelTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('main_heading', models.CharField(max_length=300, verbose_name='Main heading')),
                ('italic_text', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Intro text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='test_indepo.aboutitempluginmodel')),
            ],
            options={
                'verbose_name': 'about item plugin model Translation',
                'db_table': 'test_indepo_aboutitempluginmodel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutSectionPluginModelTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(default='About', max_length=200, verbose_name='Section title')),
                ('subtitle_part1', models.CharField(default='Find Out More', max_length=200, verbose_name='Subtitle part 1')),
                ('subtitle_part2', models.CharField(default='About Us', max_length=200, verbose_name='Subtitle part 2')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='test_indepo.aboutsectionpluginmodel')),
            ],
            options={
                'verbose_name': 'about section plugin model Translation',
                'db_table': 'test_indepo_aboutsectionpluginmodel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FaqItemPluginModelTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question', models.CharField(default='Вопрос', max_length=200, verbose_name='Question')),
                ('answer', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Answer')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='test_indepo.faqitempluginmodel')),
            ],
            options={
                'verbose_name': 'faq item plugin model Translation',
                'db_table': 'test_indepo_faqitempluginmodel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FaqSectionPluginModelTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(default='Часто задаваемые вопросы', max_length=200, verbose_name='Title')),
                ('subtitle_part1', models.CharField(default='Имеются вопросы?', max_length=200, verbose_name='Subtitle part 1')),
                ('subtitle_part2', models.CharField(default='Ознакомьтесь с нашими FAQ', max_length=200, verbose_name='Subtitle part 2')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='test_indepo.faqsectionpluginmodel')),
            ],
            options={
                'verbose_name': 'faq section plugin model Translation',
                'db_table': 'test_indepo_faqsectionpluginmodel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HeroSectionPluginModelTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title_part1', models.CharField(default='Приветствуем в', max_length=200, verbose_name='Title part 1')),
                ('title_part2', models.CharField(default='ФБГУ НИИ "Интеграл"', max_length=200, verbose_name='Title part 2')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='Ведомственная принадлежность: ФГБУ НИИ «Интеграл» находится в ведении Министерства цифрового развития, связи и массовых коммуникаций Российской Федерации', null=True, verbose_name='Description')),
                ('get_started_text', models.CharField(default='Get Started', max_length=100, verbose_name='Primary button text')),
                ('telegram_text', models.CharField(blank=True, default='Телеграмм канал', max_length=100, verbose_name='Secondary button text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='test_indepo.herosectionpluginmodel')),
            ],
            options={
                'verbose_name': 'hero section plugin model Translation',
                'db_table': 'test_indepo_herosectionpluginmodel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceTilePluginModelTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('body', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Body')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='test_indepo.servicetilepluginmodel')),
            ],
            options={
                'verbose_name': 'service tile plugin model Translation',
                'db_table': 'test_indepo_servicetilepluginmodel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
