# Generated by Django 5.2.7 on 2025-10-26 08:05

import django.db.models.deletion
import djangocms_text_ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('test_indepo', '0025_tablepluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCardItemModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200, verbose_name='Card title')),
                ('body', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='Card description')),
                ('initially_open', models.BooleanField(default=False, verbose_name='Open by default (accordion)')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AboutCardsSectionModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Section title')),
                ('layout_variant', models.CharField(choices=[('list', 'List'), ('accordion', 'Accordion')], default='list', max_length=20, verbose_name='Layout variant')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='tablepluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin'),
        ),
    ]
