# Generated by Django 5.2.7 on 2025-10-26 08:41

import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('test_indepo', '0026_aboutcarditemmodel_aboutcardssectionmodel_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipSectionModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Section title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Section description')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='LeaderItemModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full name')),
                ('job_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Position')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='Description')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=100, verbose_name='Phone')),
                ('photo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Photo')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
