# Generated by Django 5.2.7 on 2025-10-28 06:35

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_indepo', '0027_leadershipsectionmodel_leaderitemmodel'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfopluginmodel',
            name='map_preview',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Используется как заставка до загрузки карты', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Map preview image'),
        ),
    ]
