# Generated by Django 5.2.7 on 2025-10-28 07:48

import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('test_indepo', '0028_contactinfopluginmodel_map_preview'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSectionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Section title')),
                ('layout_variant', models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=20, verbose_name='Layout variant')),
                ('count', models.PositiveIntegerField(blank=True, help_text='Limit how many news cards are shown. Leave empty to show all.', null=True, verbose_name='Number of items')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NewsItemPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='News title')),
                ('short_text', models.TextField(blank=True, default='', verbose_name='Short text')),
                ('url', models.URLField(blank=True, default='', verbose_name='Link URL')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Publication date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='Open in new tab')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
