# Generated by Django 5.2.7 on 2025-10-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_indepo', '0029_newssectionpluginmodel_newsitempluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitempluginmodel',
            name='full_text',
            field=models.TextField(blank=True, default='', verbose_name='Full text'),
        ),
    ]
