# Generated by Django 5.2.7 on 2025-10-28 08:37

from django.db import migrations, models


def copy_text_from_old_fields(apps, schema_editor):
    NewsItem = apps.get_model('test_indepo', 'NewsItemPluginModel')
    for item in NewsItem.objects.all():
        source_text = getattr(item, "full_text", "") or getattr(item, "short_text", "")
        if source_text:
            item.text = source_text
            item.save(update_fields=["text"])


class Migration(migrations.Migration):

    dependencies = [
        ('test_indepo', '0030_newsitempluginmodel_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitempluginmodel',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='newsitempluginmodel',
            name='ok_url',
            field=models.URLField(blank=True, default='', verbose_name='Odnoklassniki URL'),
        ),
        migrations.AddField(
            model_name='newsitempluginmodel',
            name='tg_url',
            field=models.URLField(blank=True, default='', verbose_name='Telegram URL'),
        ),
        migrations.AddField(
            model_name='newsitempluginmodel',
            name='vk_url',
            field=models.URLField(blank=True, default='', verbose_name='VK URL'),
        ),
        migrations.RunPython(copy_text_from_old_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='newsitempluginmodel',
            name='full_text',
        ),
        migrations.RemoveField(
            model_name='newsitempluginmodel',
            name='open_in_new_tab',
        ),
        migrations.RemoveField(
            model_name='newsitempluginmodel',
            name='short_text',
        ),
        migrations.RemoveField(
            model_name='newsitempluginmodel',
            name='url',
        ),
    ]
