# Generated by Django 5.2.7 on 2025-10-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_indepo', '0031_remove_newsitempluginmodel_full_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitempluginmodel',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='newssectionpluginmodel',
            name='display_mode',
            field=models.CharField(choices=[('grid', 'Grid'), ('pagination', 'Pagination'), ('slider', 'Slider')], default='grid', max_length=12, verbose_name='Display mode'),
        ),
        migrations.AddField(
            model_name='newssectionpluginmodel',
            name='items_per_page',
            field=models.PositiveIntegerField(default=6, help_text='Used when display mode is pagination.', verbose_name='Items per page'),
        ),
    ]
