# Generated by Django 5.2.7 on 2025-10-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_indepo', '0032_newsitempluginmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitempluginmodel',
            name='link_url',
            field=models.URLField(blank=True, default='', verbose_name='External link'),
        ),
    ]
