# Generated by Django 5.2.7 on 2025-10-30 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('test_indepo', '0033_newsitempluginmodel_link_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Например: bi bi-house или любая другая иконка из вашего набора', max_length=100, verbose_name='Icon CSS class')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_icon', to='cms.page')),
            ],
            options={
                'verbose_name': 'Navigation icon',
                'verbose_name_plural': 'Navigation icons',
            },
        ),
    ]
