# Generated by Django 5.2.7 on 2025-11-11 15:07

import django.db.models.deletion
import filer.fields.file
from django.db import migrations, models


def cleanup_document_urls(apps, schema_editor):
    DocumentItem = apps.get_model("test_indepo", "DocumentItemPluginModel")
    DocumentItem.objects.exclude(file__isnull=True).update(url="")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
        ('test_indepo', '0036_alter_headerquickicon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitempluginmodel',
            name='file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.file', verbose_name='Document file'),
        ),
        migrations.AlterField(
            model_name='documentitempluginmodel',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='Document URL'),
        ),
        migrations.RunPython(cleanup_document_urls, noop),
    ]
