# Generated by Django 5.2.7 on 2025-11-11 15:23

from django.db import migrations


def cleanup_document_urls(apps, schema_editor):
    DocumentItem = apps.get_model("test_indepo", "DocumentItemPluginModel")
    DocumentItem.objects.exclude(file__isnull=True).update(url="")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('test_indepo', '0037_documentitempluginmodel_file_and_more'),
    ]

    operations = [
        migrations.RunPython(cleanup_document_urls, noop),
    ]
