# Generated by Django 5.2.7 on 2025-11-13 13:27

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('test_indepo', '0038_cleanup_document_urls'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialInitiativesSectionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Section title')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SocialInitiativeCardPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200, verbose_name='Card title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('button_label', models.CharField(default='Подробнее', max_length=120, verbose_name='Button label')),
                ('button_url', models.URLField(verbose_name='Button URL')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Icon or image')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='test_indepo.socialinitiativessectionpluginmodel')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
