# Generated by Django 5.2.7 on 2025-12-01 10:45

import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('test_indepo', '0047_alter_header_chip_opacity'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsShowcaseSectionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Section title')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='Section subtitle')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='DocumentsShowcaseCardPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200, verbose_name='Card title')),
                ('teaser', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='Teaser text')),
                ('full_text', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='Full text')),
                ('button_label', models.CharField(default='Подробнее', max_length=120, verbose_name='Button label')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Icon or image')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='test_indepo.documentsshowcasesectionpluginmodel')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
